language: python
python:
   - "2.6"
   - "2.7"


install: python setup.py install
script: python setup.py test
script: nosetests
notifications:
    email: true
    irc:
        - "irc.freenode.net#floss-seminar"
    on_success: change
    on_failure: always
